---
openapi: 3.0.1
info:
  title: API Application
  version: '1.0'
servers:
- url: http://localhost:8891
  description: Generated server url
security:
- bearer-jwt: []
paths:
  "/semester/{id}":
    get:
      tags:
      - course-controller
      operationId: getCourse
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
  "/course/{id}":
    get:
      tags:
      - course-controller
      operationId: getDetail
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Course"
  "/course-open":
    get:
      tags:
      - course-controller
      operationId: listOpen
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        courseGroup:
          type: string
        practiseGroup:
          type: string
        subjectId:
          type: integer
          format: int64
        semesterId:
          type: integer
          format: int64
        instructorId:
          type: integer
          format: int64
        maxStudents:
          type: integer
          format: int32
        remainSlot:
          type: integer
          format: int32
        currentStudents:
          type: integer
          format: int32
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
        deleted:
          type: boolean
        active:
          type: boolean
  securitySchemes:
    bearer-jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
