---
openapi: 3.0.1
info:
  title: API Application
  version: '1.0'
servers:
- url: http://localhost:8894
  description: Generated server url
security:
- bearer-jwt: []
paths:
  "/enrollment":
    get:
      tags:
      - enrollment-controller
      operationId: getList
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
components:
  securitySchemes:
    bearer-jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
