---
openapi: 3.0.1
info:
  title: API Application
  version: '1.0'
servers:
- url: http://localhost:8887
  description: Generated server url
security:
- bearer-jwt: []
paths:
  "/rooms/{id}":
    get:
      tags:
      - room-controller
      operationId: getRoomById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Room"
components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: integer
          format: int64
        roomCode:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
        deleted:
          type: boolean
        active:
          type: boolean
  securitySchemes:
    bearer-jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
