---
openapi: 3.0.1
info:
  title: API Application
  version: '1.0'
servers:
- url: http://localhost:8897
  description: Generated server url
security:
- bearer-jwt: []
paths:
  "/semester/{id}":
    get:
      tags:
      - semester-controller
      operationId: getSemesterById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Semester"
components:
  schemas:
    Semester:
      type: object
      properties:
        id:
          type: integer
          format: int64
        semesterCode:
          type: string
        semesterName:
          type: string
        majorId:
          type: integer
          format: int64
        academicYear:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        registrationStartDate:
          type: string
          format: date-time
        registrationEndDate:
          type: string
          format: date-time
        status:
          type: string
          enum:
          - UPCOMING
          - ONGOING
          - COMPLETED
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
        deleted:
          type: boolean
        active:
          type: boolean
  securitySchemes:
    bearer-jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
