---
openapi: 3.0.1
info:
  title: API Application
  version: '1.0'
servers:
- url: http://localhost:8890
  description: Generated server url
security:
- bearer-jwt: []
paths:
  "/subject/{id}":
    get:
      tags:
      - subject-controller
      operationId: getSubjectById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/Subject"
components:
  schemas:
    Subject:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subjectCode:
          type: string
        subjectName:
          type: string
        credit:
          type: integer
          format: int32
        description:
          type: string
        prerequisiteSubjects:
          type: string
  securitySchemes:
    bearer-jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
